#!/bin/sh

work_path=$(dirname $0)
cd ${work_path}

sudo rm -rf ./forDist
#sudo rm -rf ./build


#sudo pyinstaller -i ./source/images/common/icon.icns -w --clean --add-data source:source --add-data yanglabMFuns:yanglabMFuns --noconfirm --k=as2gaFgWE1weA2a --hidden-import pkg_resources.py2_warn run.py
#sudo pyinstaller -i ./source/images/common/icon.icns -w --clean --add-data source:source --add-data yanglabMFuns:yanglabMFuns --add-binary='/System/Library/Frameworks/Tk.framework/Tk':'tk' --add-binary='/System/Library/Frameworks/Tcl.framework/Tcl':'tcl' --noconfirm --k=as2gaFgWE1weA2a --hidden-import pkg_resources.py2_warn run.py


echo "============================="
echo " codesign PsyBuilder"
echo "============================="

APP_PATH="./PsyBuilder.app"
sudo codesign --deep -f -s B406553BC6044A7B8EB4EA9D42CCE348677576AE "$APP_PATH"

echo "============================="
echo " make zip for PsyBuilder"
echo "============================="

sudo mkdir "./forDist"
sudo cp -f -R $APP_PATH ./forDist/
#sudo cp -f ./doubleClickOnMeFirst ./forDist/

sudo zip -r -X "PsyBuilder$(date +%Y%m%d%H%M%S)Mac.zip" ./forDist





