#!/bin/sh

work_path=$(dirname $0)
cd ${work_path}

sudo rm -rf ./dist
sudo rm -rf ./build
sudo rm -rf ./PsyBuilder.app
sudo rm -rf ./PsyBuilder.dmg



#sudo pyinstaller -i ./source/images/common/icon.icns -w --clean --add-data source:source --add-data yanglabMFuns:yanglabMFuns --noconfirm --k=as2gaFgWE1weA2a --hidden-import pkg_resources.py2_warn psyBuilder.py
sudo pyinstaller -i ./source/images/common/icon.icns -w --clean --add-data source:source --add-data yanglabMFuns:yanglabMFuns --add-binary='/System/Library/Frameworks/Tk.framework/Tk':'tk' --add-binary='/System/Library/Frameworks/Tcl.framework/Tcl':'tcl' --noconfirm --k=as2gaFgWE1weA2a --hidden-import pkg_resources.py2_warn PsyBuilder.py

echo "============================="
echo "start to codesign the app"
echo "============================="

APP_PATH="./dist/PsyBuilder.app"
sudo codesign --deep -f -s B406553BC6044A7B8EB4EA9D42CCE348677576AE "$APP_PATH"

echo "============================="
echo "create PsyBuilder via platypus"
echo "============================="
platypus -P ./PsyBuilder.platypus -a PsyBuilder -o None -y -i ./source/images/common/icon.icns -I org.Zy.PsyBuilder -B -f ./dist/PsyBuilder.app ./PsyBuilder ..
#
#sudo mv ./dist/run.app/Contents/MacOS/run ./dist/run.app/Contents/MacOS/run0
#
#echo "====================================="
#echo "copy the bash file run into run.app"
#echo "====================================="
#
#sudo cp ./run ./dist/run.app/Contents/MacOS/
#
#sudo chmod +x ./dist/run.app

echo "============================="
echo " codesign PsyBuilder"
echo "============================="

APP_PATH="./PsyBuilder.app"
sudo codesign --deep -f -s B406553BC6044A7B8EB4EA9D42CCE348677576AE "$APP_PATH"

echo "============================="
echo " make zip for PsyBuilder"
echo "============================="

# sudo mkdir "./forDist"
# sudo cp -f -R $APP_PATH ./forDist/
#sudo cp -f ./doubleClickOnMeFirst ./forDist/

# sudo zip -r -X "PsyBuilder$(date +%Y%m%d%H%M%S)Mac.zip" $APP_PATH


echo "============================="
echo " make dmg for PsyBuilder"
echo "============================="
sudo dropdmg --config-name "psyBuilder" PsyBuilder.app

sudo mv -f ./PsyBuilder.dmg ./"PsyBuilder$(date +%Y%m%d%H%M%S).dmg"

sudo rm -rf ./PsyBuilder.app